---
- name: test
  hosts: all

  tasks:
  - name: "setup"
    setup:
    register: FACTS

  - name: "debug. msg"
    debug:
      msg:
        - "{{ ansible_hostname }},{{ ansible_system }},{{ ansible_distribution }},{{ ansible_distribution_version }}"
        #- "{{ FACTS }}"


...

